; HUD.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 3
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "TilesHud", ROM0

; Start of tile array.
Hud::
DB $FF,$FF,$81,$81,$81,$81,$81,$81
DB $81,$81,$81,$81,$81,$81,$FF,$FF
DB $FF,$FF,$99,$E7,$99,$E7,$FF,$81
DB $FF,$81,$99,$E7,$99,$E7,$FF,$FF
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00

; End of HUD.Z80
