; PANTALLA_MUERTE_TILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 106
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "TilesMuerte", ROM0

; Start of tile array.
PantallaMuerte::
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $0F,$FF,$0F,$FF,$0F,$FF,$0F,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $F0,$FF,$F0,$FF,$F0,$FF,$F0,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $F0,$FF,$F0,$FF,$F0,$FF,$F0,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $0F,$FF,$0F,$FF,$0F,$FF,$0F,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$E3,$E3
DB $E3,$E3,$E3,$E3,$E3,$E3,$E3,$E3
DB $E3,$E3,$FC,$FC,$FC,$FC,$FC,$FC
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FE,$FE,$71,$71,$71,$71,$71,$71
DB $8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F
DB $8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F
DB $8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F
DB $FF,$FF,$FF,$FF,$FF,$FF,$FE,$FE
DB $FE,$FE,$FE,$FE,$FE,$FE,$FE,$FE
DB $FF,$FF,$FF,$FF,$FF,$FF,$3F,$3F
DB $3F,$3F,$3F,$3F,$3F,$3F,$3F,$3F
DB $3F,$3F,$F8,$F8,$F8,$F8,$F8,$F8
DB $F8,$F8,$F8,$F8,$F8,$F8,$F8,$F8
DB $F8,$F8,$F8,$F8,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$1F,$1F,$1F,$1F
DB $1F,$1F,$E0,$E0,$E0,$E0,$E0,$E0
DB $F1,$F1,$F1,$F1,$8F,$8F,$8F,$8F
DB $8F,$8F,$7F,$7F,$7F,$7F,$7F,$7F
DB $8F,$8F,$F1,$F1,$F1,$F1,$F1,$F1
DB $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
DB $FF,$FF,$FF,$FF,$FF,$FF,$7F,$7F
DB $7F,$7F,$7F,$7F,$8F,$8F,$8F,$8F
DB $FF,$FF,$FF,$FF,$FF,$FF,$E0,$E0
DB $E0,$E0,$E0,$E0,$1F,$1F,$1F,$1F
DB $1F,$1F,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$E3,$E3
DB $E3,$E3,$E3,$E3,$E3,$E3,$E3,$E3
DB $E3,$E3,$E3,$E3,$E3,$E3,$E3,$E3
DB $E3,$E3,$E3,$E3,$E3,$E3,$E3,$E3
DB $E3,$E3,$E3,$E3,$E3,$E3,$E3,$E3
DB $E3,$E3,$FC,$FC,$FC,$FC,$FC,$FC
DB $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
DB $F1,$F1,$0F,$0F,$0F,$0F,$0F,$0F
DB $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
DB $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
DB $F1,$F1,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$8F,$8F,$8F,$8F,$8F,$8F
DB $FF,$FF,$FF,$FF,$FF,$FF,$F8,$F8
DB $F8,$F8,$F8,$F8,$C7,$C7,$C7,$C7
DB $C7,$C7,$C7,$C7,$C7,$C7,$C7,$C7
DB $C7,$C7,$C0,$C0,$C0,$C0,$C0,$C0
DB $C7,$C7,$C7,$C7,$C7,$C7,$C7,$C7
DB $C7,$C7,$C7,$C7,$C7,$C7,$C7,$C7
DB $E3,$E3,$E3,$E3,$E3,$E3,$E3,$E3
DB $E3,$E3,$1F,$1F,$1F,$1F,$1F,$1F
DB $FF,$FF,$FF,$FF,$FF,$FF,$1F,$1F
DB $1F,$1F,$1F,$1F,$E3,$E3,$E3,$E3
DB $FF,$FF,$FF,$FF,$FF,$FF,$F0,$F0
DB $F0,$F0,$F0,$F0,$8F,$8F,$8F,$8F
DB $8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F
DB $80,$80,$80,$80,$80,$80,$8F,$8F
DB $8F,$8F,$8F,$8F,$8F,$8F,$8F,$8F
DB $8F,$8F,$F0,$F0,$F0,$F0,$F0,$F0
DB $FF,$FF,$FF,$FF,$FF,$FF,$0F,$0F
DB $0F,$0F,$0F,$0F,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$0F,$0F,$0F,$0F,$0F,$0F
DB $F0,$F0,$F0,$F0,$F0,$F0,$F1,$F1
DB $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
DB $F0,$F0,$F0,$F0,$F0,$F0,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $01,$01,$01,$01,$01,$01,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FE,$FE,$FE,$FE,$FE,$FE,$FE,$FE
DB $FE,$FE,$FE,$FE,$FE,$FE,$FE,$FE
DB $01,$01,$01,$01,$01,$01,$FE,$FE
DB $FE,$FE,$FE,$FE,$FE,$FE,$FE,$FE
DB $FF,$FF,$FF,$FF,$FF,$FF,$38,$38
DB $38,$38,$38,$38,$38,$38,$38,$38
DB $38,$38,$38,$38,$38,$38,$38,$38
DB $38,$38,$38,$38,$38,$38,$38,$38
DB $00,$00,$00,$00,$00,$00,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $1F,$1F,$1F,$1F,$1F,$1F,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $E3,$E3,$E3,$E3,$E3,$E3,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $E3,$E3,$E3,$E3,$E0,$E0,$E0,$E0
DB $E0,$E0,$E3,$E3,$E3,$E3,$E3,$E3
DB $FC,$FC,$FC,$FC,$FC,$FC,$E3,$E3
DB $E3,$E3,$E3,$E3,$E3,$E3,$E3,$E3
DB $0F,$0F,$0F,$0F,$0F,$0F,$F1,$F1
DB $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
DB $F1,$F1,$F1,$F1,$01,$01,$01,$01
DB $01,$01,$F1,$F1,$F1,$F1,$F1,$F1
DB $F1,$F1,$F1,$F1,$F1,$F1,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $C0,$C0,$C0,$C0,$C0,$C0,$C7,$C7
DB $C7,$C7,$C7,$C7,$C7,$C7,$C7,$C7
DB $C7,$C7,$C7,$C7,$C7,$C7,$C7,$C7
DB $C7,$C7,$C7,$C7,$C7,$C7,$C7,$C7
DB $C0,$C0,$C0,$C0,$C0,$C0,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $07,$07,$07,$07,$07,$07,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $F8,$F8,$F8,$F8,$F8,$F8,$F8,$F8
DB $F8,$F8,$F8,$F8,$F8,$F8,$F8,$F8
DB $07,$07,$07,$07,$07,$07,$F8,$F8
DB $F8,$F8,$F8,$F8,$F8,$F8,$F8,$F8
DB $FF,$FF,$00,$FF,$00,$FF,$0F,$F0
DB $0F,$F0,$3F,$C0,$3F,$C0,$FF,$00
DB $FF,$FF,$FF,$FF,$FF,$FF,$F8,$FF
DB $F8,$FF,$E0,$FF,$E0,$FF,$80,$FF
DB $FF,$FF,$07,$FF,$07,$FF,$FF,$00
DB $FF,$00,$FF,$00,$FF,$00,$FF,$00
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$3F,$FF,$3F,$FF,$0F
DB $FF,$0F,$FF,$07,$FF,$07,$FF,$07
DB $FF,$07,$FF,$07,$7F,$87,$7F,$87
DB $FF,$00,$FF,$00,$0F,$F0,$0F,$F0
DB $0F,$F0,$0F,$F0,$00,$FF,$00,$FF
DB $FF,$00,$FF,$00,$FF,$00,$FF,$00
DB $FF,$00,$FF,$00,$E0,$1F,$E0,$1F
DB $80,$FF,$81,$FE,$01,$FE,$01,$FE
DB $01,$FE,$01,$FE,$01,$FE,$01,$FE
DB $01,$FE,$01,$FE,$01,$FE,$01,$FE
DB $01,$FE,$01,$FE,$01,$FE,$01,$FE
DB $E0,$1F,$E0,$1F,$FF,$00,$FF,$00
DB $FF,$00,$FF,$00,$FF,$00,$FF,$00
DB $00,$FF,$00,$FF,$0F,$F0,$0F,$F0
DB $0F,$F0,$0F,$F0,$0F,$F0,$0F,$F0
DB $7F,$87,$7F,$87,$FF,$07,$FF,$07
DB $FF,$07,$FF,$07,$FF,$07,$FF,$07
DB $FF,$07,$FF,$07,$FF,$07,$FF,$07
DB $FF,$07,$FF,$07,$FF,$07,$FF,$07
DB $0F,$F0,$0F,$F0,$0F,$F0,$0F,$F0
DB $FF,$00,$FF,$00,$FF,$00,$FF,$00
DB $FF,$00,$FF,$00,$FF,$00,$FF,$00
DB $FF,$00,$FF,$00,$FF,$00,$FF,$00
DB $01,$FE,$01,$FE,$01,$FE,$01,$FE
DB $01,$FE,$31,$FE,$31,$FE,$31,$FE
DB $FF,$00,$FF,$00,$FF,$00,$FF,$00
DB $E7,$18,$E7,$18,$87,$78,$87,$78
DB $FF,$00,$FF,$00,$FF,$00,$FF,$00
DB $FF,$00,$FF,$00,$FF,$00,$1F,$E0
DB $FF,$07,$FF,$07,$FF,$07,$FF,$07
DB $FF,$07,$FE,$07,$F8,$07,$F8,$07
DB $01,$FE,$01,$FE,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$F3,$FF,$F3,$FF
DB $86,$79,$86,$79,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$80,$FF,$80,$FF
DB $1F,$E0,$1F,$E0,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$78,$FF,$78,$FF
DB $19,$E7,$19,$E7,$00,$FF,$00,$FF
DB $00,$FF,$00,$FF,$03,$FF,$03,$FF
DB $FF,$FF,$FF,$FF,$0F,$FF,$0F,$FF
DB $3F,$FF,$3F,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$7F,$FF,$7F,$FF,$7F,$FF
DB $FF,$FF,$FF,$FF,$FC,$FF,$FC,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$E1,$E1,$E1,$E1
DB $E6,$E6,$E6,$E6,$E1,$E1,$E1,$E1
DB $E7,$E7,$E7,$E7,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$CC,$CC,$CC,$CC
DB $4C,$4C,$4C,$4C,$CC,$CC,$CC,$CC
DB $C0,$C0,$C0,$C0,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$9E,$9E,$9E,$9E
DB $9E,$9E,$9E,$9E,$9F,$9F,$9F,$9F
DB $86,$86,$86,$86,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$08,$08,$08,$08
DB $79,$79,$79,$79,$88,$88,$C8,$C8
DB $09,$09,$09,$09,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$1F,$1F,$1F,$1F
DB $9F,$9F,$9F,$9F,$1F,$1F,$1F,$1F
DB $9F,$9F,$9F,$9F,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$C0,$C0,$C0,$C0
DB $CC,$CC,$CC,$CC,$C0,$C0,$C0,$C0
DB $CC,$CC,$CC,$CC,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FC,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $1F,$FF,$1F,$FF,$1F,$FF,$FF,$FF
DB $7F,$FF,$8F,$FF,$8F,$FF,$8F,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$7F,$FF,$7F,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FC,$FF,$FC,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FE,$FF,$FE,$FF,$FE,$FF
DB $FF,$FF,$FF,$FF,$C7,$FF,$C7,$FF
DB $C7,$FF,$38,$FF,$38,$FF,$38,$FF
DB $C7,$FF,$C7,$FF,$C7,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $E3,$FF,$E3,$FF,$E3,$FF,$80,$FF
DB $80,$FF,$80,$FF,$E3,$FF,$E3,$FF
DB $FF,$FF,$FF,$E7,$FF,$E7,$FF,$00
DB $FF,$00,$FF,$E7,$FF,$E7,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$F1,$F1
DB $F1,$F1,$F1,$F1,$F1,$F1,$F1,$F1
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00

; End of PANTALLA_MUERTE_TILES.Z80
