; PREFLOP-TILES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 8
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

 SECTION "Tiles", ROMX

; Start of tile array.
PreflopLogoTiles::
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $FE,$FE,$82,$82,$82,$82,$FE,$FE
DB $80,$80,$80,$80,$80,$80,$80,$80
DB $FC,$FC,$84,$84,$84,$84,$FC,$FC
DB $E0,$E0,$90,$90,$8C,$8C,$00,$00
DB $F8,$F8,$80,$80,$80,$80,$E0,$E0
DB $80,$80,$80,$80,$F8,$F8,$00,$00
DB $F8,$F8,$80,$80,$E0,$E0,$80,$80
DB $80,$80,$80,$80,$80,$80,$00,$00
DB $80,$80,$80,$80,$80,$80,$80,$80
DB $80,$80,$80,$80,$F0,$F0,$00,$00
DB $FC,$FC,$84,$84,$84,$84,$84,$84
DB $84,$84,$84,$84,$FC,$FC,$00,$00
DB $F8,$F8,$88,$88,$88,$88,$F8,$F8
DB $80,$80,$80,$80,$80,$80,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00

; End of PREFLOP-TILES.Z80
