; TILESET_ENVIROMENT.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 27
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

SECTION "TileSets", ROM0

; Start of tile array.
TileEnvironment::
DB $00,$FF,$5D,$FF,$77,$FF,$7F,$FF
DB $47,$FF,$5F,$E7,$57,$E7,$54,$E7
DB $55,$E6,$55,$E6,$55,$E6,$55,$E6
DB $55,$E6,$55,$E6,$5D,$E6,$44,$FF
DB $00,$FF,$57,$FF,$FF,$FF,$F7,$FF
DB $EF,$FF,$FF,$FF,$FF,$FF,$7F,$FF
DB $FF,$7F,$7F,$7F,$47,$7F,$5F,$67
DB $57,$67,$57,$67,$DF,$67,$47,$FF
DB $00,$FF,$1F,$80,$1F,$80,$7F,$80
DB $78,$80,$70,$80,$70,$80,$70,$80
DB $70,$80,$70,$80,$70,$80,$78,$80
DB $7F,$80,$1F,$80,$1F,$80,$00,$FF
DB $00,$FF,$F8,$01,$F8,$01,$FE,$01
DB $1E,$01,$0E,$01,$0E,$01,$0E,$01
DB $0E,$01,$0E,$01,$0E,$01,$1E,$01
DB $FE,$01,$F8,$01,$F8,$01,$00,$FF
DB $FF,$FF,$9F,$80,$9F,$80,$E0,$9F
DB $E0,$98,$E0,$90,$E0,$90,$E0,$90
DB $E0,$90,$E0,$90,$E0,$90,$E0,$98
DB $E0,$9F,$9F,$80,$9F,$80,$FF,$FF
DB $FF,$FF,$F9,$01,$F9,$01,$07,$F9
DB $07,$19,$07,$09,$07,$09,$07,$09
DB $07,$09,$07,$09,$07,$09,$07,$19
DB $07,$F9,$F9,$01,$F9,$01,$FF,$FF
DB $19,$E4,$00,$80,$00,$00,$00,$80
DB $00,$80,$00,$80,$00,$80,$00,$00
DB $00,$80,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$80,$80,$00,$00,$80
DB $0A,$C5,$00,$01,$00,$01,$01,$00
DB $01,$00,$00,$01,$00,$01,$00,$00
DB $00,$00,$00,$00,$01,$00,$00,$01
DB $00,$01,$00,$00,$00,$01,$00,$01
DB $07,$F8,$2F,$D0,$0F,$F0,$1E,$E0
DB $0F,$F0,$07,$F8,$0F,$F0,$0D,$F2
DB $19,$E6,$1E,$E1,$1F,$E0,$12,$ED
DB $00,$FF,$03,$FF,$37,$FF,$7F,$FF
DB $E9,$00,$60,$00,$81,$00,$A3,$00
DB $C4,$03,$24,$43,$A9,$47,$61,$9F
DB $E2,$1F,$47,$BF,$C3,$3F,$47,$FF
DB $0E,$FF,$35,$FF,$DD,$FF,$FB,$FF
DB $21,$90,$00,$80,$80,$04,$02,$80
DB $40,$80,$48,$00,$00,$00,$00,$80
DB $80,$00,$00,$00,$80,$00,$00,$00
DB $00,$00,$00,$00,$80,$00,$00,$40
DB $04,$99,$00,$20,$40,$03,$00,$00
DB $01,$04,$00,$01,$00,$01,$08,$01
DB $00,$00,$00,$00,$01,$00,$01,$00
DB $00,$01,$00,$01,$01,$00,$00,$01
DB $FF,$FF,$EF,$FF,$E7,$FF,$FF,$FF
DB $BF,$FF,$DD,$FF,$FB,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
DB $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF

; End of TILESET_ENVIROMENT.Z80
